language: java
script: asdf plugin-test kotlin https://github.com/missingcharacter/asdf-kotlin.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
