language: c
script: asdf plugin-test nodejs https://github.com/missingcharacter/asdf-kotlin.git 'kotlin -version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
